# Generated by Django 5.2.1 on 2025-05-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_tasktype_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
