# Generated by Django 5.2.1 on 2025-05-14 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_alter_position_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workers",
                to="workspace.position",
            ),
        ),
    ]
