# Generated by Django 5.2.1 on 2025-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0006_team_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="workspace.task"
            ),
        ),
    ]
